name: news letter cron

on:
  workflow_dispatch:
  schedule:
    - cron: "20 23 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env file
        run: echo "${{ secrets.DOTENV }}" > .env

      - name: Run Newsletter
        run: npm run prod
